DISCORD_TOKEN = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
GENIUS_TOKEN = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MEME_USERNAME = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
MEME_PASSWORD = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
REDDIT_ID = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
REDDIT_SECRET = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
GIPHY_TOKEN = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
